### ISSUE TITLE
UX: upgrade vs update

### ISSUE THREAD

**Issue by twpayne** [toolctl/toolctl#86]
Sneaking this in now, while `toolctl` is still pre-v1.0.0.

Currently `toolctl` uses

```
$ toolctl upgrade
```
 
to update the tools managed by `toolctl` (and, if I understand correctly, also `toolctl` itself).

[Homebrew](https://brew.sh) uses `brew upgrade` to upgrade Homebrew itself, and `brew update` to update the packages managed by Homebrew. [chezmoi](https://chezmoi.io) follows a similar convention.

Is it worth renaming the `toolctl upgrade` command to `toolctl update` to match these conventions?

I'll happily submit a PR for this (although such a PR is a few renames and string substitutions, i.e. trivial).

**Comment by patrickhoefler** [comment]
Hey Tom 🙂

I'm already looking at your other PR, but I'll start with this one, because it should be quicker.

When coming up with the current `toolctl` CLI syntax, I tried to align it with tools like Homebrew and apt so that it feels as familiar as possible.

> Homebrew uses `brew upgrade` to upgrade Homebrew itself, and `brew update` to update the packages managed by Homebrew.

There is an important distinction here: 

- `brew update` and `apt update` just updates the _package definition_, not the package itself
- `brew upgrade` and `apt upgrade` installs new versions

The functionality of `toolctl upgrade` is exactly the same as `brew upgrade` or `apt upgrade`: It install new versions of one, many or all packages (including `toolctl` itself — it's just another tool, after all).

When it comes to `brew update` or `apt update`, there is currently no `toolctl` equivalent, because at the moment `toolctl` does not locally cache the tool definitions — or the "toolctl API", as I like to call it for now. By default, it always talks to the remote API, which currently consist of static YAML files hosted on GitHub.

When comparing to `chezmoi`, I'd say that `chezmoi upgrade` would be equivalent to `toolctl upgrade toolctl` — it upgrades itself.

I hope this helped clear things up a bit — let me know if I misunderstood something 🙂

**Comment by twpayne** [comment]
Thanks for the thoughtful explanation - you're right. `tool upgrade` as it is right now makes more sense. Thanks!
